### ISSUE TITLE
新发布的S怪小助手插件会把游戏给整个炸掉并且无法再次启动

### ISSUE THREAD

**Issue by HeavenPolicy** [NukoOoOoOoO/RankSSpawnHelper#2]
查看新插件的时候看到S怪农怪插件并且点了安装，游戏立刻爆炸并且无法再次正常打开游戏，重新装载了一套新的插件之后才恢复

**Comment by NukoOoOoOoO** [comment]
过段时间应该会收到更新推送，你可以试一下。我问了一下用的人他们说1.4.2在加载的时候是没问题的

**Comment by HeavenPolicy** [comment]
> 过段时间应该会是没刷更新的问题，你可以一下子。

非常感谢，期待您的更新
